version: '3'
services:
  web:
    build: .
    ports:
      - '4000:4000'
  db:
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    volumes:
      - db-data:/foo
volumes:
  db-data:
